env:
  global:
    - CC_TEST_REPORTER_ID=97a3a93eebbf0bca588722d6d67809a1bdf1c7f142cd0070a5e33dd79aeb6d94
  
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install poetry
  - pip install flake8
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
# command to run tests
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test
  - make cov-test
after_script:
  - ./cc-test-reporter after-build format-coverage coverage.xml -t coverage.py -r CC_TEST_REPORTER_ID 
